version: "3.9"

services:
  db-postgres:
    image: postgres:13-alpine
    container_name: db-postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
      ADD_LEDGER_DATA: ${ADD_LEDGER_DATA}
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  postgres-db:
